### ISSUE TITLE
Add Python virtual environment (venv) to deploy dashboard

### ISSUE THREAD

**Issue by gryckelynck** [landryb/dashboard#1]
Hello Landry,
It would be nice to have a virtual environment to easily deploy the dashboard.

**Comment by gryckelynck** [comment]
List of required Python modules I've identified :
- bootstrap-Flask
- celery
- redis
- flask
- owslib
- sqlalchemy

**Comment by landryb** [comment]
yes, that's ... mentioned in the readme :)
```
apt install python3-flask-bootstrap python3-flask python3-celery
```
but you're right, maybe i've forgotten some..

**Comment by fphg** [comment]
checked : dashboard runs on python 3.10 virtualenv (3.9 broken)

as usual :

python3.10 -m venv venv
./venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt

**Comment by landryb** [comment]
3.9 won't work mostly because i use the [`match`)(https://docs.python.org/3/reference/compound_stmts.html#match) keyword (switch/case blocks) which is the only 'recent' feature of python i know of, could be easy to replace that by an ugly `if/elif/elif/else` construct
